// <auto-generated />
using FluentApi.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FluentApi.Migrations
{
    [DbContext(typeof(DbModelContext))]
    [Migration("20210325130956_InsertData")]
    partial class InsertData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FluentApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categpria")
                        .IsRequired();

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100);

                    b.Property<string>("Imagen")
                        .HasMaxLength(150);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Precio");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Categpria = "Manuales", Descripcion = "Esta es la descripcion del martillo", Imagen = "https://images-na.ssl-images-amazon.com/images/I/71tTWyypTKL._AC_SY355_.jpg", Nombre = "Martillo", Precio = 23.32 },
                        new { Id = 2, Categpria = "Electricas", Descripcion = "Esta es la descripcion del Taladro", Imagen = "https://cajonherramientas.com/wp-content/uploads/2019/09/taladro-inalambrico-articulo.jpg", Nombre = "Taladro", Precio = 98.32 },
                        new { Id = 3, Categpria = "Electricas", Descripcion = "Esta es la descripcion de la Motosierra", Imagen = "https://nogalpark.com/archivos/recortes/motosierra-stihl-ms780-nogalpark-1502817726.jpg", Nombre = "Motosierra", Precio = 50.03 },
                        new { Id = 4, Categpria = "Manuales", Descripcion = "Esta es la descripcion del juego de desarmadores", Imagen = "https://images-na.ssl-images-amazon.com/images/I/610-syUEk2L._AC_SY355_.jpg", Nombre = "Juego de Desarmadores", Precio = 9.42 },
                        new { Id = 5, Categpria = "Puertas", Descripcion = "Esta es la descripcion de la puerta de madera pino", Imagen = "https://c0.klipartz.com/pngpicture/813/444/gratis-png-ventana-jeld-wen-puerta-muebles-madera-puertas-madera.png", Nombre = "Puerta de Madera Pino", Precio = 132.42 },
                        new { Id = 6, Categpria = "Puertas", Descripcion = "Esta es la descripcion de la puerta de Hierro", Imagen = "https://images-na.ssl-images-amazon.com/images/I/71DqYPPOJEL._AC_SY355_.jpg", Nombre = "Puerta de Hierro", Precio = 10.42 },
                        new { Id = 7, Categpria = "Puertas", Descripcion = "Esta es la descripcion de la puerta de madera cedro", Imagen = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZjLG5l8K9zw_UCf7xaSQs1JRgMlrR-XL6Jw&usqp=CAU", Nombre = "Puerta de Madera cedro", Precio = 100.42 },
                        new { Id = 8, Categpria = "Electricas", Descripcion = "Esta es la descripcion de la amoladora bosch", Imagen = "https://s3.amazonaws.com/mercado-ideas/wp-content/uploads/sites/2/2018/09/24214558/amoladora-el%C3%A9ctrica.png", Nombre = "Amoladora marca bosch", Precio = 80.42 },
                        new { Id = 9, Categpria = "Electricas", Descripcion = "Esta es la descripcion de la cortadora dewalt", Imagen = "https://cms.grupoferrepat.net/assets/img/productos/D28730-B3.jpg", Nombre = "Cortadora marca dewalt", Precio = 122.42 },
                        new { Id = 10, Categpria = "Manuales", Descripcion = "Esta es la descripcion del mazo de acero", Imagen = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKKXtR0CvezGN0hVvYFxbLuXhIRV-MmJPFsA&usqp=CAU", Nombre = "Mazo de acero", Precio = 12.42 },
                        new { Id = 11, Categpria = "Manuales", Descripcion = "Esta es la descripcion del mazo de madera", Imagen = "https://thumbs.dreamstime.com/b/peque%C3%B1o-mazo-de-madera-26098974.jpg", Nombre = "Mazo de madera", Precio = 5.42 },
                        new { Id = 12, Categpria = "Manuales", Descripcion = "Esta es la descripcion de la tijera de acero inoxidable", Imagen = "https://images-na.ssl-images-amazon.com/images/I/318J5mHXGTL._AC_.jpg", Nombre = "Tijera de acero inoxidable", Precio = 6.42 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
